export const NEW_CATRGORY_REQUEST = "NEW_CATRGORY_REQUEST";
export const NEW_CATRGORY_SUCCESS = "NEW_CATRGORY_SUCCESS";
export const NEW_CATRGORY_RESET = "NEW_CATRGORY_RESET";
export const NEW_CATRGORY_FAIL = "NEW_CATRGORY_FAIL";

export const ALL_CATEGORY_REQUEST = "ALL_CATEGORY_REQUEST";
export const ALL_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS";
export const ALL_CATEGORY_RESET = "ALL_CATEGORY_RESET";
export const ALL_CATEGORY_FAIL = "ALL_CATEGORY_FAIL";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

export const DETAIL_CATEGORY_REQUEST = "DETAIL_CATEGORY_REQUEST";
export const DETAIL_CATEGORY_SUCCESS = "DETAIL_CATEGORY_SUCCESS";
export const DETAIL_CATEGORY_RESET = "DETAIL_CATEGORY_RESET";
export const DETAIL_CATEGORY_FAIL = "DETAIL_CATEGORY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
