export const ADD_USER_ORDER_REQUEST = "ADD_USER_ORDER_REQUEST";
export const ADD_USER_ORDER_SUCCESS = "ADD_USER_ORDER_SUCCESS";
export const ADD_USER_ORDER_FAILURE = "ADD_USER_ORDER_FAILURE";

export const GET_USER_ORDER_REQUEST = "GET_USER_ORDER_REQUEST";
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS";
export const GET_USER_ORDER_FAILURE = "GET_USER_ORDER_FAILURE";

export const GET_USER_ORDER_DETAILS_REQUEST = "GET_USER_ORDER_DETAILS_REQUEST";
export const GET_USER_ORDER_DETAILS_SUCCESS = "GET_USER_ORDER_DETAILS_SUCCESS";
export const GET_USER_ORDER_DETAILS_FAILURE = "GET_USER_ORDER_DETAILS_FAILURE";
